

# Warning, this makefile assert that you have correctly set SS_CC
SS_CC=/usr/ensta/pack/simplescalar-3v0d/bin/sslittle-na-sstrix-gcc

CC=${SS_CC}

all:
	$(CC) -o add_vec.ss add_vectors.c

clean:
	rm add_vec.ss


